# Generated by Django 3.1.1 on 2020-09-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quartos', models.PositiveSmallIntegerField()),
                ('num_salas_estar', models.PositiveSmallIntegerField()),
                ('num_salas_jantar', models.PositiveSmallIntegerField()),
                ('area', models.PositiveSmallIntegerField()),
                ('num_vagas_garagem', models.PositiveSmallIntegerField()),
                ('possui_armario_embutido', models.BooleanField(default=None)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('aluguel', models.PositiveIntegerField()),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.PositiveSmallIntegerField()),
                ('cidade', models.CharField(max_length=25)),
                ('uf', models.CharField(max_length=2)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imvwb.bairro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quartos', models.PositiveSmallIntegerField()),
                ('num_salas_estar', models.PositiveSmallIntegerField()),
                ('num_salas_jantar', models.PositiveSmallIntegerField()),
                ('area', models.PositiveSmallIntegerField()),
                ('num_vagas_garagem', models.PositiveSmallIntegerField()),
                ('possui_armario_embutido', models.BooleanField(default=None)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('aluguel', models.PositiveIntegerField()),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.PositiveSmallIntegerField()),
                ('cidade', models.CharField(max_length=25)),
                ('uf', models.CharField(max_length=2)),
                ('andar', models.PositiveSmallIntegerField()),
                ('valor_condominio', models.PositiveSmallIntegerField()),
                ('possui_portaria_24h', models.BooleanField(default=None)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imvwb.bairro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
